### ISSUE TITLE
Unable to append statements to a function

### ISSUE THREAD

**Issue by kyyash** [dsherret/ts-simple-ast#458]
**Describe the bug**
Version: X.X.X

Unable to append statements to a function. 
**To Reproduce**

Add a statement to MethodDeclaration, works for first time but we try to append one more statement with add statement method or insert statement method, I get,
doManipulation.js:11 Uncaught Error: Cannot read property 'compilerNode' of undefined
Text: "...t() {\r\n  }\r\n  /*functions*/\r\n  handleMethod(arg) {\n      console.log(5);\r\n  /*events*/\r\n  }\r\n\r\n}\r\n\n    console.log(\"6\");"

**Expected behavior**

I must be able to append the statement.
handleMethod(arg) {
  /*statements*/
      console.log(5);
     console.log(6);
  }

**Comment by dsherret** [comment]
Hey, could you add some code that reproduces the problem? I may be able to figure it out as-is, but reproduction code would help. Thanks!

**Comment by kyyash** [comment]
let methodDeclaration = classDeclaration.getMethod(functionName);
					let statementArray=<Statement[]>methodDeclaration.getStatements();
					methodDeclaration.insertStatements(statementArray.length,bodyText);

this adds the console log for the first execution, if these statements execute again on the same ast model,

i get this stack trace,

typescript.parser.ts:422 Error: Cannot read property 'compilerNode' of undefined
-- Details --
Path: /__temp__.ts
Text: "...t() {\r\n  }\r\n  /*functions*/\r\n  handleEvents(event) {\n      console.log(5);\r\n  /*events*/\r\n  }\r\n\r\n}\r\n\n    console.log(5);"
    at InvalidOperationError.BaseError [as constructor] (BaseError.js:8)
    at new InvalidOperationError (InvalidOperationError.js:9)
    at Object.doManipulation (doManipulation.js:11)
    at Object.insertIntoParentTextRange (insertion.js:16)
    at SyntaxList.insertChildText (SyntaxList.js:53)
    at MethodDeclaration.StatementedNode.class_1.insertStatements (StatementedNode.js:39)
    at TypescriptParser.appendToFunction (typescript.parser.ts:416)
    at VDOMPageService.doActionAddListener (vdom.page.service.ts:618)
    at VDOMPageService.doAction (vdom.page.service.ts:403)
    at VDOMPageService.doActions (vdom.page.service.ts:372)

**Comment by dsherret** [comment]
@kyyash could you modify this code until the problem happens?

```ts
const project = new Project();
const sourceFile = project.createSourceFile("test.ts", "class MyClass {\n    myMethod() {\n    }\n}");
const methodDeclaration = sourceFile.getClassOrThrow("MyClass").getMethodOrThrow("myMethod");

for (let i = 0; i < 10; i++)
    methodDeclaration.addStatements("console.log(5);");
```

In that error message, the code in there like `/functions/\r\n` seems very suspect. Why are there regular expression literals like that in the code?

**Comment by kyyash** [comment]
Here is the function code that changes step by step after manipulation,
1. initial state
  /*functions*/
  handleEvents(event) {
  /*events*/
  }

2. After invoking addStatements or insertStatement API using MethodDeclaration,
  /*functions*/
  handleEvents(event) {
      if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}
  /*events*/
  }
3. After invoking the same API second time, for instance to add the same set of statements again i.e,
IfStatement. , I noticed that nothing changed,

  /*functions*/
  handleEvents(event) {
      if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}
  /*events*/
  }
**But this time I get this error,**
typescript.parser.ts:426 Error: Cannot read property 'compilerNode' of undefined
-- Details --
Path: /__temp__.ts
Text: "... \"UPDATE_CHART\"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}\r\n  /*events*/\r\n  }\r\n\r\n}\r\n\n    if(event.eventType === \"UPDATE_CHART\"){this.inputCtrlext_chartp2khuaambajmzu1chj=event.payload;}"
    at InvalidOperationError.BaseError [as constructor] (BaseError.js:8)
    at new InvalidOperationError (InvalidOperationError.js:9)
    at Object.doManipulation (doManipulation.js:11)
    at Object.insertIntoParentTextRange (insertion.js:16)
    at SyntaxList.insertChildText (SyntaxList.js:53)
    at MethodDeclaration.StatementedNode.class_1.insertStatements (StatementedNode.js:39)
    at TypescriptParser.appendToFunction (typescript.parser.ts:422)
    at VDOMPageService.doActionAddListener (vdom.page.service.ts:579)
    at VDOMPageService.doAction (vdom.page.service.ts:403)
    at VDOMPageService.doActions (vdom.page.service.ts:372)

**Comment by dsherret** [comment]
@kyyash why does the code have the regular expression literals in the middle of it (ex. `/events/`)? Are you meaning to use comments? That's not syntactically correct js/ts code. For example, look at this AST:

![image](https://user-images.githubusercontent.com/1609021/46593093-db6c1980-ca96-11e8-93fc-6049d31d3361.png)

**Comment by dsherret** [comment]
@kyyash oh ok. Code blocks are helpful to use on github. There might be some useful information that was stripped from your previous posts: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

I will see if I can reproduce this sometime this week, but a reproducible example using the code I previously posted in [this comment](https://github.com/dsherret/ts-simple-ast/issues/458#issuecomment-427686741) as a template, would speed up the process of finding the problem.

**Comment by dsherret** [comment]
@kyyash I'm not able to reproduce so I'll need a reproducible example in order to fix this. Please use [github code blocks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting). Here's a template to help start from (please modify this code until the problem happens so that I am able to reproduce the problem):

```ts
const project = new Project({ useVirtualFileSystem: true });
const sourceFile = project.createSourceFile("test.ts", `class Test {
    /*functions*/
    handleEvents(event) {
    /*events*/
    }
}`);
const method = sourceFile.getClassOrThrow("Test").getMethodOrThrow("handleEvents");

method.addStatements(`if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}`);
method.addStatements(`if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}`);
```

Note: That does reproduce the same bug as #189, but it doesn't lead to the error mentioned in this issue.

Thanks!

**Comment by dsherret** [comment]
Unfortunately I have not been able to reproduce this one so I'm closing it for now. See my last comment for details on how reproducing the bug could be helped. Please reopen this if you can provide those details.

**Comment by kyyash** [comment]
`import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import {ActivatedRoute} from '@angular/router';
import {RestService, EventBus, Authentication, IGadgetConfiguration} from '@sag-asd-modules/gadget-framework';
import {NotificationsService} from 'angular2-notifications';
import { ISNGGridOption } from 'asd-common/icommon.models';
import * as $ from 'jquery';
import * as prefData from '../../../preferences.json';

/*imports*/

@Component({
  selector: 'app-page_kk3rfu44wbbjnx4wsdk',
  templateUrl: './page_kk3rfu44wbbjnx4wsdk.component.html',
  styleUrls: ['./page_kk3rfu44wbbjnx4wsdk.component.css']
})
export class Page_kk3rfu44wbbjnx4wsdkPage implements OnInit {
/*field-declaration*/

  constructor(private restService: RestService, private notificationsService: NotificationsService, private eventBus: EventBus) {
  /*field-init*/
  this.eventBus.listener().subscribe(this.handleEvents.bind(this));
  }

  ngOnInit() {
  }
  /*functions*/
  handleEvents(event) {
  /*events*/
  }

}`

**Comment by kyyash** [comment]
vdom.page.service.ts:578 Error: Debug Failure. False expression.
    at Object.setTextPos (typescript.js:7526)
    at addSyntheticNodes (typescript.js:110819)
    at createSyntaxList (typescript.js:110841)
    at processNodes (typescript.js:110804)
    at visitNodes (typescript.js:15128)
    at Object.forEachChild (typescript.js:15358)
    at SourceFileObject.NodeObject.forEachChild (typescript.js:110781)
    at createChildren (typescript.js:110813)
    at SourceFileObject.NodeObject.getChildren (typescript.js:110758)
    at SourceFile.Node.getCompilerChildren (Node.js:1313)

**Comment by kyyash** [comment]
> `import { Component, OnInit } from '@angular/core';
> import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
> import {ActivatedRoute} from '@angular/router';
> import {RestService, EventBus, Authentication, IGadgetConfiguration} from '@sag-asd-modules/gadget-framework';
> import {NotificationsService} from 'angular2-notifications';
> import { ISNGGridOption } from 'asd-common/icommon.models';
> import * as $ from 'jquery';
> import * as prefData from '../../../preferences.json';
> 
> /_imports_/
> 
> @component({
> selector: 'app-page_kk3rfu44wbbjnx4wsdk',
> templateUrl: './page_kk3rfu44wbbjnx4wsdk.component.html',
> styleUrls: ['./page_kk3rfu44wbbjnx4wsdk.component.css']
> })
> export class Page_kk3rfu44wbbjnx4wsdkPage implements OnInit {
> /_field-declaration_/
> 
> constructor(private restService: RestService, private notificationsService: NotificationsService, private eventBus: EventBus) {
> /_field-init_/
> this.eventBus.listener().subscribe(this.handleEvents.bind(this));
> }
> 
> ngOnInit() {
> }
> /_functions_/
> handleEvents(event) {
> /_events_/
> }
> 
> }`

I had posted the ts content and the error message i get

**Comment by dsherret** [comment]
@kyyash I fixed the code in those posts to properly format the code. You need to use three backticks like this when editing the markdown...

````ts
```ts
// code goes here
```
````

...but the code above still shows regular expression literals in it (ex. `/_functions_`).

I'm still unable to reproduce this problem though. If you would like this fixed, then please take this template and edit it until the error message occurs:

```ts
const project = new tsSimpleAst.Project({ useVirtualFileSystem: true });
const sourceFile = project.createSourceFile("test.ts", `import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import {ActivatedRoute} from '@angular/router';
import {RestService, EventBus, Authentication, IGadgetConfiguration} from '@sag-asd-modules/gadget-framework';
import {NotificationsService} from 'angular2-notifications';
import { ISNGGridOption } from 'asd-common/icommon.models';
import * as $ from 'jquery';
import * as prefData from '../../../preferences.json';

/*imports*/

@Component({
  selector: 'app-page_kk3rfu44wbbjnx4wsdk',
  templateUrl: './page_kk3rfu44wbbjnx4wsdk.component.html',
  styleUrls: ['./page_kk3rfu44wbbjnx4wsdk.component.css']
})
export class Page_kk3rfu44wbbjnx4wsdkPage implements OnInit {
/*field-declaration*/

  constructor(private restService: RestService, private notificationsService: NotificationsService, private eventBus: EventBus) {
  /*field-init*/
  this.eventBus.listener().subscribe(this.handleEvents.bind(this));
  }

  ngOnInit() {
  }
  /*functions*/
  handleEvents(event) {
  /*events*/
  }

}`);
const method = sourceFile.getClassOrThrow("Page_kk3rfu44wbbjnx4wsdkPage").getMethodOrThrow("handleEvents");

method.addStatements(`if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}`);
method.addStatements(`if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}`);

console.log(sourceFile.getFullText());
```

**Comment by kyyash** [comment]
@dsherret  I didnt understand your comment. 

I can tell you that issue with code formatting, same code works if it is in different format.
I am trying to add a property at class level,
it works for this ts file,
`import {
  Component,
  OnInit
} from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams
} from '@angular/common/http';
import {
  ActivatedRoute
} from '@angular/router';
import {
  RestService,
  EventBus,
  Authentication,
  IGadgetConfiguration
} from '@sag-asd-modules/gadget-framework';
import {
  NotificationsService
} from 'angular2-notifications';
import {
  ISNGGridOption
} from 'asd-common/icommon.models';
import * as $ from 'jquery';
import * as prefData from '../../../preferences.json'; /*imports*/
@Component({
  selector: 'app-page_kk3rfu44wbbjnx4wsdk',
  templateUrl: './page_kk3rfu44wbbjnx4wsdk.component.html',
  styleUrls: ['./page_kk3rfu44wbbjnx4wsdk.component.css']
}) export class Page_kk3rfu44wbbjnx4wsdkPage implements OnInit { /*field-declaration*/
  constructor(private restService: RestService, private notificationsService: NotificationsService, private eventBus: EventBus) { /*field-init*/
    this.eventBus.listener().subscribe(this.handleEvents.bind(this));
  }
  ngOnInit() {} /*functions*/
  handleEvents(event) { /*events*/ }
}`

For the same ts content but slightly different format, it does not work, cannot add an attribute at class level,

`import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import {ActivatedRoute} from '@angular/router';
import {RestService, EventBus, Authentication, IGadgetConfiguration} from '@sag-asd-modules/gadget-framework';
import {NotificationsService} from 'angular2-notifications';
import { ISNGGridOption } from 'asd-common/icommon.models';
import * as $ from 'jquery';
import * as prefData from '../../../preferences.json';

/*imports*/

@Component({
  selector: 'app-page_kk3rfu44wbbjnx4wsdk',
  templateUrl: './page_kk3rfu44wbbjnx4wsdk.component.html',
  styleUrls: ['./page_kk3rfu44wbbjnx4wsdk.component.css']
})
export class Page_kk3rfu44wbbjnx4wsdkPage implements OnInit {
/*field-declaration*/

  constructor(private restService: RestService, private notificationsService: NotificationsService, private eventBus: EventBus) {
  /*field-init*/
  this.eventBus.listener().subscribe(this.handleEvents.bind(this));
  }

  ngOnInit() {
  }
  /*functions*/
  handleEvents(event) {
  /*events*/
  }

}`

**Comment by kyyash** [comment]
works fine for same ts content but with slight different code formatting,
`import {
  Component,
  OnInit
} from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams
} from '@angular/common/http';
import {
  ActivatedRoute
} from '@angular/router';
import {
  RestService,
  EventBus,
  Authentication,
  IGadgetConfiguration
} from '@sag-asd-modules/gadget-framework';
import {
  NotificationsService
} from 'angular2-notifications';
import {
  ISNGGridOption
} from 'asd-common/icommon.models';
import * as $ from 'jquery';
import * as prefData from '../../../preferences.json'; /*imports*/
@Component({
  selector: 'app-page_kk3rfu44wbbjnx4wsdk',
  templateUrl: './page_kk3rfu44wbbjnx4wsdk.component.html',
  styleUrls: ['./page_kk3rfu44wbbjnx4wsdk.component.css']
}) export class Page_kk3rfu44wbbjnx4wsdkPage implements OnInit { /*field-declaration*/
  constructor(private restService: RestService, private notificationsService: NotificationsService, private eventBus: EventBus) { /*field-init*/
    this.eventBus.listener().subscribe(this.handleEvents.bind(this));
  }
  ngOnInit() {} /*functions*/
  handleEvents(event) { /*events*/ }
}`

**Comment by dsherret** [comment]
@kyyash I'm sorry, but I can't reproduce. Please ensure you are using the latest version of ts-simple-ast and then try out this code:

```ts
import { Project, ts } from "ts-simple-ast";

console.log(ts.version); // mine is 3.1.6

const project = new Project({ useVirtualFileSystem: true });
const sourceFile = project.createSourceFile("test.ts", `import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import {ActivatedRoute} from '@angular/router';
import {RestService, EventBus, Authentication, IGadgetConfiguration} from '@sag-asd-modules/gadget-framework';
import {NotificationsService} from 'angular2-notifications';
import { ISNGGridOption } from 'asd-common/icommon.models';
import * as $ from 'jquery';
import * as prefData from '../../../preferences.json';

/*imports*/

@Component({
  selector: 'app-page_kk3rfu44wbbjnx4wsdk',
  templateUrl: './page_kk3rfu44wbbjnx4wsdk.component.html',
  styleUrls: ['./page_kk3rfu44wbbjnx4wsdk.component.css']
})
export class Page_kk3rfu44wbbjnx4wsdkPage implements OnInit {
/*field-declaration*/

  constructor(private restService: RestService, private notificationsService: NotificationsService, private eventBus: EventBus) {
  /*field-init*/
  this.eventBus.listener().subscribe(this.handleEvents.bind(this));
  }

  ngOnInit() {
  }
  /*functions*/
  handleEvents(event) {
  /*events*/
  }

}`);
const method = sourceFile.getClassOrThrow("Page_kk3rfu44wbbjnx4wsdkPage").getMethodOrThrow("handleEvents");

method.addStatements(`if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}`);
method.addStatements(`if(event.eventType === "UPDATE_CHART"){this.inputCtrlext_charte1bz6m77qojmztz4pb=event.payload;}`);

console.log(sourceFile.getClassOrThrow("Page_kk3rfu44wbbjnx4wsdkPage").getConstructors()[0].getText());
console.log(sourceFile.getFullText());
```

Please modify that example, change it to reproduce the bug, then repost it back here. I can't help without proper reproduction steps and a contained example. Thanks!

**Comment by kyyash** [comment]
@dsherret 
I tried to upgrade the typescript version in the package.json, for some reason it still shows 3.0.1
this is the output I get when execute the generated js file using 'node'
Adjust glob pattern(s) in the 'outFiles' attribute so that they cover the generated JavaScript.
node --inspect-brk=29111 ts.parser.test.js 
Debugger listening on ws://127.0.0.1:29111/a783c819-93f8-4619-9c25-05046d3b7618
For help, see: https://nodejs.org/en/docs/inspector
3.0.1
ts.parser.test.ts:3
TypeError: ts_simple_ast_1.Project is not a constructor
ts.parser.test.ts:5
    at Object.<anonymous> (c:\Codebase\sag-ts-parser\ts.parser.test.ts:5:17)
    at Module._compile (internal/modules/cjs/loader.js:699:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)

**Comment by kyyash** [comment]
I was able to run your code snippet after upgraded simple ast to 18.0.

In addition,

I see that simple ast is not backward compatible with its own versions may be due to its ongoing changes.

if (importDeclnStructure.namedImports.indexOf(element.getText()) !== -1)

indexOf does not work here anymore after upgrading to simple ast 18.0.0

**Comment by kyyash** [comment]
one more observation,
When I try to add a statement to a function, second time i face the issue,
typescript.parser.ts:460 Error: Cannot read property 'compilerNode' of undefined
-- Details --
Path: /__temp__.ts
Text: "...= \"UPDATE_CHART\"){this.inputCtrlext_charth5r7p0w0qjo4bgiiw=event.payload;}\r\n  /*events*/\r\n  }\r\n\r\n}\r\n\n      if(event.eventType === \"UPDATE_CHART\"){this.inputCtrlext_chartzuvip2e5h9jo4bh9q5=event.payload;}"
    at InvalidOperationError.BaseError [as constructor] (BaseError.js:8)
    at new InvalidOperationError (InvalidOperationError.js:9)
    at Object.doManipulation (doManipulation.js:12)
    at Object.insertIntoParentTextRange (insertion.js:15)
    at SyntaxList.insertChildText (SyntaxList.js:53)
    at MethodDeclaration.StatementedNode.class_1.insertStatements (StatementedNode.js:39)
    at MethodDeclaration.StatementedNode.class_1.addStatements (StatementedNode.js:35)
    at TypescriptParser.appendToFunction (typescript.parser.ts:451)


I tried debugging doManipulation.js

I found that in this line,
nodeHandler.handleNode(sourceFile, replacementSourceFile, replacementSourceFile);
replacementSourcFile.getFullText() shows my statement got added outside the class instead of inside the function.

**Comment by dsherret** [comment]
@kyyash yes, between version 14 and 18 there will be breaking changes. The project uses semantic versioning: https://semver.org

Please post the error messages and code in github code blocks: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting -- the error messages you're posting show regex literals.

I've still been unable to reproduce this bug. Were you able to modify this example to reproduce it? https://github.com/dsherret/ts-simple-ast/issues/458#issuecomment-435399281 -- Please do that if you want a quick fix. Thanks!

**Comment by kyyash** [comment]
`core.js:1449 ERROR Error: Cannot read property 'compilerNode' of undefined
-- Details --
Path: /__temp__.ts
Text: "...\"UPDATE_CHART\"){this.inputCtrlext_chartlq3dt5mrebsjo4f142u=event.payload;}\r\n  /*events*/\r\n  }\r\n\r\n}\r\n\n      if(event.eventType === \"UPDATE_CHART\"){this.inputCtrlext_chart07qs1oqgxtvhjo4f1gai=event.payload;}"
    at InvalidOperationError.BaseError [as constructor] (BaseError.js:8)
    at new InvalidOperationError (InvalidOperationError.js:9)
    at Object.doManipulation (doManipulation.js:12)
    at Object.insertIntoParentTextRange (insertion.js:15)
    at SyntaxList.insertChildText (SyntaxList.js:53)
    at MethodDeclaration.StatementedNode.class_1.insertStatements (StatementedNode.js:39)
    at MethodDeclaration.StatementedNode.class_1.addStatements (StatementedNode.js:35)
    at TypescriptParser.appendToFunction (typescript.parser.ts:452)
    at VDOMPageService.doActionAddListener (vdom.page.service.ts:667)
    at VDOMPageService.doAction (vdom.page.service.ts:472)`

**Comment by kyyash** [comment]
```
core.js:1449 ERROR Error: Cannot read property 'compilerNode' of undefined
-- Details --
Path: /__temp__.ts
Text: "...\"UPDATE_CHART\"){this.inputCtrlext_chartlq3dt5mrebsjo4f142u=event.payload;}\r\n  /*events*/\r\n  }\r\n\r\n}\r\n\n      if(event.eventType === \"UPDATE_CHART\"){this.inputCtrlext_chart07qs1oqgxtvhjo4f1gai=event.payload;}"
    at InvalidOperationError.BaseError [as constructor] (BaseError.js:8)
    at new InvalidOperationError (InvalidOperationError.js:9)
    at Object.doManipulation (doManipulation.js:12)
    at Object.insertIntoParentTextRange (insertion.js:15)
    at SyntaxList.insertChildText (SyntaxList.js:53)
    at MethodDeclaration.StatementedNode.class_1.insertStatements (StatementedNode.js:39)
    at MethodDeclaration.StatementedNode.class_1.addStatements (StatementedNode.js:35)
    at TypescriptParser.appendToFunction (typescript.parser.ts:452)
    at VDOMPageService.doActionAddListener (vdom.page.service.ts:667)
    at VDOMPageService.doAction (vdom.page.service.ts:472)
```

**Comment by dsherret** [comment]
@kyyash is the code accidentally calling `addStatements` somewhere with an extra close brace (`}`)?

**Comment by kyyash** [comment]
no @dsherret, I had checked it , nothing extra there,

your code snippet posted in comment
https://github.com/dsherret/ts-simple-ast/issues/458#issuecomment-435399281
works fine for me in always but once I start using it into my code , i did console before and after
I still face issue.

how can I enable source map for simple ast so that I can debug myself ?
