### ISSUE TITLE
Property `getAssertClause` does not exist on type `ImportDeclaration`

### ISSUE THREAD

**Issue by bennycode** [dsherret/ts-simple-ast#1484]
**Describe the bug**

Version: 21.0.1

**To Reproduce**

When upgrading from ts-morph v20 to v21 the `getAssertClause` is no longer available on an `ImportDeclaration`:

```ts
import {Project, SyntaxKind} from 'ts-morph';

const project = new Project();

project.getSourceFiles().forEach(sourceFile => {
  sourceFile.getImportDeclarations().forEach(importDeclaration => {
    importDeclaration.getDescendantsOfKind(SyntaxKind.StringLiteral).forEach(() => {
      // It fails here:
      console.log(importDeclaration.getAssertClause());
    });
  });
});
```

**Expected behavior**

I wish to call this method but I couldn't find any hint in the release notes where to find it now: https://github.com/dsherret/ts-morph/releases

**Comment by bennycode** [comment]
@dsherret can you give me a hint what I can use instead of `getAssertClause()`?

**Edit:** [Telling from this change](https://github.com/dsherret/ts-morph/pull/1476/files#diff-0245100212211916ccab36ece23dfbfaa1c0e2d08c0fa5cb4e7292a717720ec7) I have to call `getAttributes()` now? I guess this is because TS 5.3 updated to the import attributes proposal ([source](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#import-attributes)).

**Comment by bennycode** [comment]
Ok, I am using `getAttributes()` now but it would be nice to know how to find assert clauses in legacy code. I would need it to write a codemod that can convert the old `assert {type: 'json'}` syntax into `with {type: 'json'}`.
